# Generated by Django 2.0.5 on 2018-06-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180610_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='votes',
        ),
        migrations.AddField(
            model_name='ratinglist',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Rate'),
        ),
    ]
