# Generated by Django 2.0.5 on 2018-06-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180611_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rate_text',
        ),
    ]
