# Generated by Django 2.0.5 on 2018-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_rate_rate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
