# Generated by Django 2.0.5 on 2018-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
