# Generated by Django 2.0.5 on 2018-06-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180612_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='quote',
        ),
    ]
