# Generated by Django 2.0.5 on 2018-06-12 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180612_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='The World', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default='President', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='quote',
            field=models.CharField(default='Welcome', max_length=200),
            preserve_default=False,
        ),
    ]
