# Generated by Django 2.0.5 on 2018-06-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180612_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
    ]
