# Generated by Django 2.0.5 on 2018-06-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180612_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='quote',
        ),
    ]
