# Generated by Django 2.0.5 on 2018-06-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_candidate_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.FileField(upload_to='candidate_photo'),
        ),
    ]
