# Generated by Django 2.0.5 on 2018-06-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
